#!/usr/bin/env node
/**
 * Reads version from package.json and writes src/version.ts.
 * Run as a prebuild step so SPEC_VERSION is always in sync.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(__dirname, '../package.json'), 'utf-8'));

const content = `// AUTO-GENERATED by scripts/gen-version.js — do not edit manually.
export const SPEC_VERSION: string = '${pkg.version}';
`;

writeFileSync(join(__dirname, '../src/version.ts'), content);
console.log(`✓ Generated src/version.ts → SPEC_VERSION = '${pkg.version}'`);
